# This is a simple version of installing opencv and tesseract in Dockerfile 

FROM python:3.7 

RUN apt-get update -y 

RUN apt-update && apt install -y libsm6 libxext6 

RUN apt-get -y install tesseract-ocr 
